name: ExportPack
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  Pack:
    runs-on: ubuntu-latest
    steps:
      - uses: FrostBanditTeam/extract-unity-package-action@1
      - name: pack cl
        with:
          unityProjectPath: ./
          packagePath: Assets
          outputPackagePath: ./artifacts/output.unitypackage
